# Generated by Django 3.2.19 on 2023-07-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20230719_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
